# Initialising the theme variable lets Github know which Static Site Generator we're using
theme: jekyll-theme-minimal
title: Arrnav Dutta - Aspiring Actuary and an Avid Gamer
description: Arrnav Dutta's Actuarial Exam Progress, Blogs, Gaming Adventures and more!